name: Update key version

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Update v value in JSON
        run: |
          FILE="API's/versionFilm.json"
          
          CURRENT_V=$(grep -o 'v=[0-9]*' "$FILE" | grep -o '[0-9]*')
          
          if [ -z "$CURRENT_V" ]; then
            CURRENT_V=3
          fi
          
          NEW_V=$((CURRENT_V + 1))
          
          sed -i "s/&v=[0-9]*/\&v=$NEW_V/" "$FILE"
          
          echo "Actualizado v=$CURRENT_V → v=$NEW_V"

      - name: Commit and push
        run: |
          FILE="API's/versionFilm.json"
          NEW_V=$(grep -o 'v=[0-9]*' "$FILE" | grep -o '[0-9]*')
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$FILE"
          git diff --cached --quiet || git commit -m "Update key v=$NEW_V"
          git push
